[build]
  command = "echo 'Static site - no build required'" 
  publish = "."  

[[redirects]]
  from = "/account/*"
  to = "/account/index.html"
  status = 200

[[redirects]]
  from = "/*.html"
  to = "/:splat.html"
  status = 200