[build]
  command = ""
  publish = "."
[[redirects]]
  from = "/account/*"
  to = "/account/index.html"
  status = 200
  force = true
[[redirects]]
  from = "/account/"
  to = "/account/login"
  status = 301
[[redirects]]
  from = "/account/index"
  to = "/account/login"
  status = 301